Newmac calibration scumonlymac
PisterLab/scum-test-code pull request #37
Opened 2022-11-18 17:18 UTC by filmak

Features of this PR:

- MAC for multi-hop scum networking
- functions for toggling all 16 GPIOs
- skeleton for a scum-only network (currently only two scum)

2022-11-18 18:01 UTC, daniellovell requested changes

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/applications/freq_sweep_tx_simple/freq_sweep_tx_simple.c
> +		packet[0] = app_vars.index;
Fil says this is not necessary

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/applications/freq_sweep_tx_simple/freq_sweep_tx_simple.uvprojx
> +          <PackID>ARM.CMSIS.5.7.0</PackID>
Will review if this change causes is issues...

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/radio.c
> +//#define DIV_ON
This should become a configuration parameter of the radio init, #def probably not the best way

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/radio.c
> +		gpio_12_set();
Remove GPIO toggles inside radio -Fil

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/radio.c
> +				gpio_14_toggle();
Remove

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/radio.c
> +void receive_packet_indefinitely(uint8_t pkt_len) {
Document that its a blocking wait for a packet

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/rftimer.c
> +    //ICER = 0x80;
Is this ok? Needs testing

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/scm3c_hw_interface.c
> -#define INIT_HF_CLOCK_FINE          17
Remove changes of board-specific values

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/radio.c
> +    //if(packet_len == radio_vars.rxPacket_len && radio_getCrcOk()) {
Proposal to have receive_packet_length(uint8_t packet_len) and receive_packet(void) where the latter does not know a priori the length to expect and does not check it.

2022-11-18 18:01 UTC, daniellovell commented on scm_v3c/applications/freq_sweep_rx/freq_sweep_rx.c
> -        app_vars.packet_len == LEN_RX_PKT && (radio_getCrcOk())
Restore packet_len check

2022-11-21 19:59 UTC, daniellovell commented on scm_v3c/applications/freq_sweep_tx_simple/freq_sweep_tx_simple.uvprojx
> +          <PackID>ARM.CMSIS.5.7.0</PackID>
This is fine as far as I can tell in my testing. My Keil automatically changes the pack ID to ARM.CMSIS.5.3.0, so I had no issues building.

2022-11-21 20:03 UTC, daniellovell commented on scm_v3c/scm3c_hw_interface.c
> -#define INIT_HF_CLOCK_FINE          17
Fixed in e6eeb40567b76b6e8c1851f27788de37049cf0a9

2022-11-21 21:27 UTC, daniellovell commented on scm_v3c/radio.c
> +		gpio_12_set();
Done in 8cc73b30b98c561e0eee2eb3df5beb06b6cf01e1

2022-11-22 01:04 UTC, daniellovell commented on scm_v3c/rftimer.c
> +    //ICER = 0x80;
Addressed by a0b02cebde38e6f564c9355ee45211c3c370a974

2022-11-22 07:17 UTC, daniellovell commented on scm_v3c/radio.c
> +    //if(packet_len == radio_vars.rxPacket_len && radio_getCrcOk()) {
Implemented in dd1e918347eb80e30ab1b1c1f82230a4d2b77e00

2022-11-30 10:46 UTC, filmak commented on scm_v3c/applications/freq_sweep_tx_simple/freq_sweep_tx_simple.c
> +		packet[0] = app_vars.index;
Yes, reverting this change is fine. I was using the index to do PDR testing. What I should really do is make a new project explicitly for PDR testing.

2022-11-30 10:58 UTC, filmak commented on scm_v3c/radio.c
> +    //if(packet_len == radio_vars.rxPacket_len && radio_getCrcOk()) {
In my protocols I effectively rewrite "receive packet" and the "endframe_cb" so any changes are fine. I believe that many of the radio example applications do use these. if I'm understanding the changes correctly, they should work.

2022-11-30 14:33 UTC, filmak commented on scm_v3c/rftimer.c
> +    //ICER = 0x80;
These changes do not seem to influence the operation of my protocols. I'm not sure if it's necessary, but I individually enable_by_id each RFTimer compare interrupt.

2022-12-15 22:41 UTC, merged